name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Run Application
      run: java -cp target/java-cicd-1.0.jar App

    - name: Create deployment package
      run: zip -r deploy.zip Procfile target/java-cicd-1.0.jar

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v1
      with:
        application_name: cicd
        environment_name: cicd-env
        region: us-east-1
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        deployment_package: deploy.zip
